// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgC4llQHEfh6hB3SJBSg9XXIdMwqI1KMo',
    appId: '1:42402778500:web:866874c68c01bc0ac2e1d1',
    messagingSenderId: '42402778500',
    projectId: 'twitterclone-26c84',
    authDomain: 'twitterclone-26c84.firebaseapp.com',
    storageBucket: 'twitterclone-26c84.firebasestorage.app',
    measurementId: 'G-56TSJDVEK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa5nU3tjcsFJL36fHlm0gx3rQHq3IypR4',
    appId: '1:42402778500:android:361cfdd0e93437ebc2e1d1',
    messagingSenderId: '42402778500',
    projectId: 'twitterclone-26c84',
    storageBucket: 'twitterclone-26c84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR6LQP13ZlEhyOopDn_1vbP0XxYg-gIsY',
    appId: '1:42402778500:ios:b5796f080d5c8942c2e1d1',
    messagingSenderId: '42402778500',
    projectId: 'twitterclone-26c84',
    storageBucket: 'twitterclone-26c84.firebasestorage.app',
    iosBundleId: 'com.example.twitterClone',
  );
}
